CONFIG_NAME: 'lightweight'

DATASET_NAME: 'flower'
DATA_DIR: 'E:\anhang\Lightweight-Manipulation-master\data\flower\flower'
GPU_ID: '0'
WORKERS: 4


TREE:
    BRANCH_NUM: 3


TRAIN:
    FLAG: True
    NET_G: ''
    B_NET_D: True
    BATCH_SIZE: 32 #36
    MAX_EPOCH: 600
    SNAPSHOT_INTERVAL: 5
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002
    #
    NET_E: 'E:\anhang\Lightweight-Manipulation-master\DAMSMencoders\flower\text_encoder195.pth'
    SMOOTH:
        GAMMA1: 4.0  
        GAMMA2: 5.0
        GAMMA3: 10.0 
        LAMBDA: 5.0


GAN:
    DF_DIM: 64
    GF_DIM: 32
    Z_DIM: 100
    R_NUM: 2

TEXT:
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 10
